services:
  urt-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urt-server
    user: "${UID:-1000}:${GID:-1000}"
    command: [ "./server-run.sh" ]
    network_mode: host
    volumes:
      - .:/usr/src/urt
    environment:
      - MALLOC_CHECK_=0
      - GLIBC_TUNABLES=glibc.malloc.check=0
    restart: unless-stopped
